config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

  resources :posts

  resources :tags do
  	get 'posts' => 'posts#search'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps


  def save_tag(sent_tags)
  	current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
  	old_tags = current_tags - sent_tags
  	new_tags = sent_tags - current_tags

  	old_tags.each do |old|
  		self.tags.delete Tag.find_by(tag_name: old)
  	end

  	new_tags.each do |new|
  		new_post_tag = Tag.find_or_create_by(tag_name: new)
  		self.tags << new_post_tag
  	end

  end

end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
	has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(nil)
    if @post.save
      @post.save_tag(tag_list)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
	end

	def index
		@posts = Post.all
		#@tags = @post.tag.find(params[:tag_id])
		#@post_tags = @tags.all
		@tag_list = Tag.all
		post = Post.new
		@user = current_user
	end

	def show
		@post = Post.find(params[:id])
		@post_tags = @post.tags
	end

	def search
		@tag_list= Tag.all
		@tag = Tag.find(params[:tag_id])
		@posts = @tag.posts.all
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		post = Post.find(params[:id])
		post.update(post_params)
		redirect_to post_path(post.id)
	end

	def destroy
		post = Post.find(params[:id])
		post.destroy
		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:content)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">

		<h3>投稿編集</h3>
			<%= form_with(model: @post, url: posts_path, method: :destroy, local: true) do |f| %>
				<%= f.text_area :content %>
				<br>
				<p>スペースを入力することで複数のタグをつけることが出来ます。</p>
				<P>例：音楽 文芸 スポーツ</P>
				<%= f.text_field :tag_name %>
				<%= f.submit '編集', class: "btn btn-primary" %>
			<% end %>

		<%= link_to '投稿詳細', post_path(@post) %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">

	<div class="row">
		<p>Welcome! <%= @current_user.name %>さん!</p>
	</div>

	<div class="row">
		<h3>タグリスト</h3>
			<% @tag_list.each do |list| %>
				<%= link_to tag_posts_path(tag_id: list.id) do %>
					<%= list.tag_name %>(<%= list.posts.count %>)
				<% end %>
			<% end %>

		<hr>
		<div class="new_post">
			<h3>新規投稿</h3>
				<%= form_with(model: Post.new, url: posts_path, local: true) do |f| %>
					<%= f.text_area :content %>
					<br>
					<p>スペースを入力することで複数のタグをつけることが出来ます。</p>
					<P>例：音楽 文芸 スポーツ</P>
					<%= f.text_field :tag_name %>
					<%= f.submit '投稿', class: "btn btn-primary" %>
				<% end %>
		</div>

		<hr>
		<h3>投稿一覧</h3>
			<% @posts.each do |post| %>
				<div class="post_index">
					<%= link_to post.content, post_path(post.id) %>

				</div>
			<% end %>

	</div>

</div>

app/views/posts/search.html.erb
<div class="container">
	<div class="row">
		<h2>投稿一覧</h2>

		<% @tag_list.each do |list| %>
			<%= link_to list.tag_name, tag_posts_path(post_tag_id: list.id) %>

		<% end %>

		</br>
		<span>タグが - </span><%= @tag.tag_name %><span> - の投稿一覧</span>
		</br>
		<% @posts.each do |post| %>

			<%= link_to post.content, post_path(post.id) %>
		</br>
		<% end %>

	</div>

	<div class="row">
		<%= link_to 'ホーム', root_path %>
	</div>

</div>

app/views/posts/show.html.erb
<div class="container">

	<div class="posts">
		<h1>投稿詳細</h1>
		<h3>内容</h3>
			<%= @post.content %>
		<h3>タグ</h3>
			<% @post_tags.each do |tag| %>
				<%= link_to tag_posts_path(tag_id: tag.id) do %>
				<%= tag.tag_name %>(<%= tag.posts.count %>)
			<% end %>
		<% end %>

	</div>

	<hr>
	<div class="post_edit">
		<p>投稿編集</p>
		<%= link_to "編集", edit_post_path(@post.id), class: "btn btn-default" %>
		<%= link_to "削除", post_path(@post.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
	</div>

	<hr>
	<%= link_to 'ホーム', root_path %>

</div>